#!/bin/bash
#
# Copyright (c) 2012 Jackie Jin(liveaeon@gmail.com). All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


readonly SCRIPT_DIR="$(dirname "$0")"
readonly SCRIPT_DIR_ABS="$(cd "${SCRIPT_DIR}" ; pwd -P)"

#modify it to the correctly NACL path
export NACL_SDK_ROOT=$HOME/tools/nacl_sdk/
#   NACL_TARGET_PLATFORM="pepper_16"
export NACL_TARGET_PLATFORM="pepper_16"

readonly NACL_PLATFORM_DIR="${NACL_SDK_ROOT}/${NACL_TARGET_PLATFORM}"
readonly BASE_SCRIPT="${NACL_PLATFORM_DIR}/third_party/scons-2.0.1/script/scons"

export SCONS_LIB_DIR="${NACL_PLATFORM_DIR}/third_party/scons-2.0.1/engine"
export PYTHONPATH="${NACL_PLATFORM_DIR}/third_party/scons-2.0.1/engine"
# We have to do this because scons overrides PYTHONPATH and does not preserve
# what is provided by the OS.  The custom variable name won't be overwritten.
export PYMOX="${NACL_PLATFORM_DIR}/third_party/pymox"

"${BASE_SCRIPT}" --file=build.scons \
                 --site-dir="${NACL_PLATFORM_DIR}/build_tools/nacl_sdk_scons" \
                 $*

